export class AddProductDialogObjects {
  protected static MANUAL_ENTRY_BUTTON = `text="Manual entry"`;
  protected static DAY_PASS_BUTTON = `text="Day pass"`;
  protected static DPP_NAME_TEXT_FIELD = `[placeholder="10 day passes package"]`;
  protected static DPP_NUMBER_OF_PASSES_TEXT_FIELD = `input[type="number"][placeholder="10"]`;
  protected static HPP_NAME_TEXT_FIELD = `[placeholder="100 hours package"]`;
  protected static HPP_NUMBER_OF_PASSES_TEXT_FIELD = `input[type="number"][placeholder="100"]`;
  protected static BCPP_NAME_TEXT_FIELD = `[placeholder="$500 Booking credit package"]`;
  protected static BCPP_NUMBER_OF_PASSES_TEXT_FIELD = `input[type="number"][placeholder="500"]`;
  protected static HOURLY_PASS_PACKAGE_BUTTON = `text="Hourly pass package"`;
  protected static BOOKING_CREDIT_PACKAGE_BUTTON = `text="Booking credit package"`;
  protected static ADD_PRODUCT_BUTTON  = `text="Add product"`;
  protected static CLOSE_BUTTON = `.euiFlyoutFooter .euiButtonEmpty.css-1igwkce-euiButtonDisplay-euiButtonEmpty-m-empty-primary-flush-left .euiButtonEmpty__text`;
  protected static PRODUCT_NAME_TEXT_FIELD = `input[data-test-subj="product_Name"]`;
  protected static PRODUCT_DESCRIPTION_TEXT_FIELD = `textarea[data-test-subj="product_Description"]`;
  protected static SAVE_CHANGES_BUTTON = `text="Save changes"`;
  protected static SAVE_CHANGES_DISABLED_BUTTON = `.euiButton-isDisabled`;
  protected static TOAST_ERROR_TEXT = `.euiToast [data-test-subj="euiToastBody"]`;
  protected static CLOSE_RETURN_BUTTON = `[aria-label="Close this dialog"]`;
  protected static CLOSE_RETURN_BOTTOM_BUTTON = `text="Close"`;
  protected static DISCARD_UNSAVED_CHANGES_BUTTON = `text="Discard unsaved changes"`;
  protected static PRODUCT_SAVE_ERROR = '.euiFormErrorText';
  protected static FINANCIAL_ACCOUNTS_DROP_DOWN_MENU = "[data-test-subj='product_FinancialAccountId']";
  protected static TAX_RATE_DROP_DOWN_MENU = "[data-test-subj='product_TaxRateId']";
  protected static DELETE_BUTTON = `text=Delete`;
  protected static CONFIRMATION_BUTTON = `text="Yes, do it"`;
  protected static CONFIRMATION_TEXT = `[data-test-subj="euiToastHeader__title"]`;
  protected static MORE_ACTIONS_BUTTON = `text="More actions"`;
  protected static COPY_PRODUCT_BUTTON = `text="Copy product"`;
  protected static CLOSE_NOTIFICATION_TOAST_BUTTON = `[data-test-subj="toastCloseButton"]`;
  protected static ADJUST_STOCK_BUTTON = `text="Adjust stock"`;
  protected static STOCK_LEVEL_TEXT_FIELD = `.euiModal .euiFieldNumber`;
  protected static ASSIGN_TO_RESOURSES_BUTTON = `text="Assign to resources"`;
  protected static PRODUCT_NAME_HEADER = `.euiTitle`;
  protected static PRODUCT_LOCATION_TEXT_FIELD = `[value="Coworking Soho (DENIS)"]`;
  protected static PRODUCT_DESCRIPTION_TEXT_AREA = `[data-test-subj="product_Description"]`;
  protected static PRODUCT_UNIT_PRICE_TEXT_FIELD = `[data-test-subj="product_Price"]`;
  protected static BENEFITS_TAB = `text="Benefits"`;
  protected static INTEGRATIONS_TAB = `text="Integrations"`;
  protected static AVAILABILITYS_TAB = `text="Availability"`;
  protected static BENEFITS_BUTTON = `text="Benefits"`;
  protected static PRINTING_CREDIT_HEADER_BUTTON = `text="Printing credit"`;
  protected static PRINTING_CREDIT_BUTTON = `text="Add printing credit"`;
  protected static PRINTING_CREDIT_NAME_TEXT_FIELD = `[data-test-subj="comboBoxSearchInput"]`;
  protected static PRINTING_CREDIT_TIME_TEXT_FIELD = `.euiFieldNumber`;
  protected static CREDIT_DESCRIPTION_TEXT_FIELD = `[data-test-subj="productBookingCredit_Name"]`;
  protected static CREDIT_AMOUNT_TEXT_FIELD = `[data-test-subj="productBookingCredit_Credit"]`;
  protected static CREDIT_NAME = `text="creditName"`;
  protected static PRODUCT_CHECK_BOX = `[aria-labelledby="productBookingCredits"] [aria-label="Select row 1"]`;
  protected static DELETE_PRODUCT_BUTTON = `text="Delete 1 record"`;
  protected static CLOSE_LIST_OF_OPTIONS = `[aria-label="Close list of options"]`;
  protected static DISABLED_INTEGRATION_BUTTON = `[data-test-subj="product_SyncToAppName"][aria-checked="false"]`;
  protected static ENABLED_INTEGRATION_BUTTON = `[data-test-subj="product_SyncToAppName"][aria-checked="true"]`;
  protected static ENABLED_MONITOR_STOCK_LEVEL_FOR_PRODUCT_BUTTON = `[aria-checked="true"][data-test-subj="product_TrackStock"]`;
  protected static DISABLED_MONITOR_STOCK_LEVEL_FOR_PRODUCT_BUTTON = `[aria-checked="false"][data-test-subj="product_TrackStock"]`;
  protected static MONITOR_STOCK_LEVEL_FOR_PRODUCT_BUTTON = `[data-test-subj="product_TrackStock"]`;
  protected static PRINTING_CREDIT_NAME_BUTTON = `text="printingCreditName"`;
  protected static PRINTING_CREDIT_AMOUNT_BUTTON = `text="printingCreditAmount"`;
  protected static PASSES_CREDIT_HEADER_BUTTON = `text="Passes"`;
  protected static ADD_PASSES_BUTTON = `text="Add pass"`;
  protected static PASSES_NAME_TEXT_FIELD = `[data-test-subj="comboBoxSearchInput"]`;
  protected static PASSES_NAME_TEXT_FIELD_PARAM = `[data-test-subj="productTimePass_TimePassId"]`;
  protected static PASSES_AMOUNT_TEXT_FIELD = `.euiFieldNumber`;
  protected static PASSES_NAME_BUTTON = `text="passesCreditName"`;
  protected static PASSES_AMOUNT_BUTTON = `text="passesCreditAmount"`;
  protected static TIME_CREDIT_HEADER_BUTTON = `text="Time credit"`;
  protected static ADD_TIME_CREDIT_BUTTON = `text="Add time credit"`;
  protected static TIME_CREDIT_NAME_TEXT_FIELD = `[data-test-subj="comboBoxSearchInput"]`;
  protected static TIME_CREDIT_AMOUNT_TEXT_FIELD = `.euiFieldNumber`;
  protected static TIME_CREDIT_NAME_BUTTON = `text="timeCreditName"`;
  protected static TIME_CREDIT_AMOUNT_BUTTON = `text="timeCreditAmount"`;
  protected static MONEY_CREDIT_HEADER_BUTTON = `text="Money credit"`;
  protected static ADD_MONEY_CREDIT_BUTTON = `text="Add money credit"`;
  protected static MONEY_CREDIT_NAME_TEXT_FIELD = `[data-test-subj="productBookingCredit_Name"]`;
  protected static MONEY_CREDIT_AMOUNT_TEXT_FIELD = `[data-test-subj="productBookingCredit_Credit"]`;
  protected static MONEY_CREDIT_NAME_BUTTON = `text="moneyCreditName"`;
  protected static MONEY_CREDIT_AMOUNT_BUTTON = `text="moneyCreditAmount"`;
  protected static RESOURCES_DROP_DOWN_MENU = `text="Select resources"`;
  protected static RESOURCE_NAME_MENU_OPTION = `.euiFilterSelectItem[title="resourseName"]`;
  protected static RESOURCES_DROP_DOWN_MENU_LIST_OF_OPTIONS = `[aria-label="Open list of options"][data-test-subj="comboBoxToggleListButton"]`;
  protected static ASSIGN_TO_RESOURCES_DIALOG_TEXT = `[data-test-subj="confirmModalBodyText"]`;
  protected static STOCK_LEVEL_ALERT_TEXT_FIELD = `.euiFieldNumber`;
  protected static PREVENT_STOCK_FALL_BELOW_ZERO_DISABLED_BUTTON = `button#AllowNegativeStock[aria-checked="false"]`;
  protected static DISPLAY_PRODUCT_BUTTON = `[data-test-subj="product_Visible"]`;
  protected static DELETE_TEXT_FIELD = `[placeholder="Type 'DELETE' to continue"]`;
  protected static BULK_ACTIONS_BUTTON = '//*[contains(text(),"Text")]';
  protected static DELETE_RECORD_BUTTON_SIDE_MENU = '//*[contains(text(),"Text")]';
  protected static DELETE_RECORD_TEXT_FIELD = '[placeholder="Type \'DELETE\' to continue"]';
  protected static PRODUCT_KIND_MENU = '[name="SystemProductType"]';
  protected static PRODUCT_KIND = '[data-test-subj="product_SystemProductType"]';
}
